anidb: Fix & more options

diff --git a/anidb b/anidb
--- a/anidb
+++ b/anidb
@@ -3,28 +3,42 @@
 CLIENT=animeta
 CLIENT_VER=1
 CACHE_DIR=~/.cache/anidb
+[ -f ~/.config/anidb ] && source ~/.config/anidb
 mkdir -p $CACHE_DIR
 
 usage() {
     cat <<EOM
 Usage:
-    anidb <anime_id>
+    anidb [OPTIONS] <anime_id>
+
+OPTIONS:
+    --format <format>
+        yaml, json (by default)
+
+    --force
+        ignore cache
 
 See: https://anidb.net/
 EOM
     exit
 }
 
-[ $# -ne 1 ] && usage
-
-fetch_xml() {
-    curl -s "http://api.anidb.net:9001/httpapi?client=${CLIENT}&clientver=${CLIENT_VER}&protover=1&request=anime&aid=15293" |
-        gunzip -d
+join() {
+    awk 'BEGIN { FS = RS; RS = "@@@@@@@@@@" }
+    {
+        for (i = 1; i < NF - 1; ++i)
+            printf("%s / ", $i);
+        print($(NF-1))
+    }'
 }
 
 xml() {
-    [ -f $CACHE_DIR/$1.xml ] || fetch_xml > $CACHE_DIR/$1.xml
-    cat $CACHE_DIR/$1.xml
+    aid=$1
+    if [ ! -f $CACHE_DIR/$aid.xml ] ; then
+        curl "http://api.anidb.net:9001/httpapi?client=${CLIENT}&clientver=${CLIENT_VER}&protover=1&request=anime&aid=$aid" |
+            gunzip -d > $CACHE_DIR/${aid}.xml
+    fi
+    cat $CACHE_DIR/$aid.xml
 }
 
 term() {
@@ -46,7 +60,8 @@ yaml() {
     xml $aid | web-grep '<episodecount>{}</episodecount>'
 
     term title
-    xml $aid | web-grep '<titles><title xml:lang=ja>{}</title></titles>'
+    xml $aid | web-grep '<titles><title xml:lang=ja>{}</title></titles>' |
+        join
 
     term date
     echo
@@ -60,10 +75,64 @@ yaml() {
     term cast
     echo
     xml $aid | web-grep '<seiyuu>{}</seiyuu>' | sed 's/^/- /g'
+
+    term company
+    echo
+    xml $aid | web-grep '<name type="Animation Work">{}</name>' | sed 's/^/- /g'
+
+    term picture
+    echo
+    xml $aid | web-grep '<picture>{}</picture>' | sed 's/^/- /g'
 }
 
 json() {
-    yaml $1 | yaml2json
+    aid=$1
+    if [ ! -f $CACHE_DIR/$aid.json ]; then
+        yaml $1 | yaml2json > $CACHE_DIR/$aid.json
+    fi
+    cat $CACHE_DIR/$aid.json
 }
 
-json "$1"
+FORMAT=json
+FORCE=0
+AID=
+
+while [ $# -gt 0 ]; do
+    case "$1" in
+        -h | --help )
+            usage
+            ;;
+        --format )
+            FORMAT=$2
+            shift 2
+            ;;
+        --force )
+            FORCE=1
+            shift
+            ;;
+        * )
+            AID=$1
+            shift
+            ;;
+    esac
+done
+
+if [ -z "$AID" ]; then
+    usage
+fi
+
+if [ $FORCE -eq 1 ]; then
+    rm -f $CACHE_DIR/$AID.*
+fi
+
+case "$FORMAT" in
+    json )
+        json "$AID"
+        ;;
+    yaml )
+        yaml "$AID"
+        ;;
+    * )
+        echo "Error: Unknown format $FORMAT"
+        exit 1
+esac
